language: java
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:gluster/glusterfs-3.8 -y
  - sudo apt-get update -qq -y
  - sudo apt-get install -y build-essential libtool pkg-config automake glusterfs-server
after_script:  bash catlogs.sh
notifications:
  email: false
